scicatUrl: "http://scicat.localhost/api/v3/"
facilityCollectionIDs:
  FACILITY-1: aaa00000-00bb-dd11-bb55-9999f4444444
  FACILITY-2: 6666ffff-ee55-44ee-aaff-55554444bb22
  otheruni: 33332222-7799-4477-bbbb-5555bbbb5555
globusScopes: 
  - "urn:globus:auth:scope:transfer.api.globus.org:all[*https://auth.globus.org/scopes/aaa00000-00bb-dd11-bb55-9999f4444444/data_access]"
  - "urn:globus:auth:scope:transfer.api.globus.org:all[*https://auth.globus.org/scopes/6666ffff-ee55-44ee-aaff-55554444bb22/data_access]"
  - "urn:globus:auth:scope:transfer.api.globus.org:all[*https://auth.globus.org/scopes/33332222-7799-4477-bbbb-5555bbbb5555/data_access]"
port: 8080
facilitySrcGroupTemplate: "SRC-{{ .FacilityName }}"
facilityDstGroupTemplate: "DST-{{ .FacilityName }}"
